#!/bin/bash
set -euo pipefail
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    SELECT 'CREATE DATABASE ${AIRFLOW_DB}'
    WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = '${AIRFLOW_DB}')\gexec
    GRANT ALL PRIVILEGES ON DATABASE ${AIRFLOW_DB} TO ${POSTGRES_USER};
EOSQL
